# Generated by Django 4.2.4 on 2023-10-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storelogin',
            old_name='password',
            new_name='ownerpassword',
        ),
    ]
