# Generated by Django 4.2.4 on 2023-10-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0003_storelogin_address_storelogin_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelogin',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
