# Generated by Django 4.2.4 on 2023-10-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0004_storelogin_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelogin',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
    ]
