# Generated by Django 4.2.4 on 2023-10-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewaste', '0005_storelogin_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='storelogin',
        ),
    ]
